<?php
/**
 * Created by PhpStorm.
 * User: KTA30
 * Date: 11/8/14
 * Time: 1:05 PM
 */



/*function custommodule_init(){
    echo 'Today: \n';
    echo date('m/d/Y');
   
}*/

function custommodule_preprocess_node(&$variables) {
    $node = $variables['node'];

    if (  $variables['node']->type == 'dynamic_content') {
        $variables['title'] = FALSE;
        $variables['content']['links'] = FALSE;

    }
}



