<?php
/**
 * Created by PhpStorm.
 * User: KTA30
 * Date: 11/8/14
 * Time: 1:05 PM
 */



function custommodule_init(){
/*
    $x=arg();
	$query = new EntityFieldQuery();
	


	$query->entityCondition('entity_type', 'node')
	  ->entityCondition('bundle', 'product')
	  ->propertyCondition('status', NODE_PUBLISHED)
	 //->propertyCondition('field_product_category','value',  '27' , '=')
	  //->fieldCondition('field_news_types', 'value', 'spotlight', '=')
	  //->fieldCondition('field_photo', 'fid', 'NULL', '!=')
	 // ->fieldCondition('field_faculty_tag', 'tid', $value)
	 // ->fieldCondition('field_news_publishdate', 'value', $year . '%', 'like')
	  //->fieldOrderBy('field_priority', 'value', 'DESC')
	  ->range(0, 100)
	  ->addMetaData('account', user_load(1)); // Run the query as user 1.

	$result = $query->execute();
	
	if (isset($result['node'])) {
	  $news_items_nids = array_keys($result['node']);
	  $news_items = entity_load('node', $news_items_nids);
	

		foreach($news_items as $row){
			echo $row->title."<br>";
			echo $row->body['und'][0]['value']."<br>";
			
		}
	}
	
 */  
}

function custommodule_preprocess_node(&$variables) {
    $node = $variables['node'];

    if (  $variables['node']->type == 'dynamic_content') {
        $variables['title'] = FALSE;
        $variables['content']['links'] = FALSE;

    }
}



function custommodule_form_alter(&$form, &$form_state, $form_id) {

    if ($form_id == 'user_login') {
        $form['name']['#attributes']['placeholder'] = t( 'Username' );
        $form['name']['#description'] = t('');
        $form['pass']['#description'] = t('');
        $form['pass']['#attributes']['placeholder'] = t( 'Password' );
        $form['#prefix'] = '<h2> <span>Log</span> in</h2>';
        //$form['#suffix'] = '<span class="sign-up-text">Forgot Your Password? <a href="'.$GLOBALS['base_url'].'/user/password"> Click Here</a></span></div>';
    }
	if ($form_id == 'user_register_form') {
        //$form['account']['name']['#attributes']['placeholder'] = t( 'Desired Username' );
		$form['account']['name']['#description'] = t('');
        //$form['account']['mail']['#attributes']['placeholder'] = t( 'E-mail' );
		$form['account']['mail']['#description'] = t('');
        $form['#prefix'] = '<h2> <span>Sign</span> up </h2>';
        //$form['#suffix'] = '<span class="sign-up-text">Already Have An Account With Heroez Fit?<a href="'.$GLOBALS['base_url'].'/user/login"> Login</a></span></div>';
	}
	
	if($form_id == 'category_node_form'){
		$x=arg();
		if($x[2]=='edit')
            $form['#prefix'] = '<h2> Edit Category </h2>';
		else
			$form['#prefix'] = '<h2> Add Category </h2>';
			
		$form['actions']['submit']['#submit'][] = 'MYMODULE_submit_category';
	}

    if($form_id == 'product_node_form'){

		$form['base']['model']['#description'] = '';
        $form['taxonomy_catalog']['#type'] = 'hidden';
        $form['base']['prices']['list_price']['#type'] = 'hidden';
        $form['base']['prices']['cost']['#type'] = 'hidden';
        $form['base']['shippable']['#type'] = 'hidden';
        $form['base']['prices']['sell_price']['#title'] = 'Price';
        $form['base']['prices']['sell_price']['#description'] = '';
        $form['base']['ordering']['#description'] = '';


        $x=arg();
        if($x[2]=='edit')
            $form['#prefix'] = '<h2>Edit Product</h2>';
        else
            $form['#prefix'] = '<h2>Add Product</h2>';
        
		$form['actions']['submit']['#submit'][] = 'MYMODULE_submit_product';


    }
	
	
	
}


function MYMODULE_submit_category ($form, &$form_state) {
    //code here
    $form_state['redirect'] = '/category-listing'; //REDIRECTS TO STEP 2 after submit
}

function MYMODULE_submit_product ($form, &$form_state) {
    //code here
    $form_state['redirect'] = '/product-admin-list'; //REDIRECTS TO STEP 2 after submit
}

